spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_pedidos_db
spring.datasource.username=postgres
spring.datasource.password=Admin1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
